### ISSUE TITLE
Unable to add to the list

### ISSUE THREAD

**Issue by domaxi** [AY2021S1-CS2113-T13-2/tp#219]
<img width="1440" alt="Screenshot 2020-10-30 at 4 14 18 PM" src="https://user-images.githubusercontent.com/60168552/97678773-531e9e00-1acf-11eb-93f1-4ff576f28751.png">

Hi, I am trying to use your application, I followed how to use the add command, but I cannot use it

**Comment by TomLBZ** [comment]
Hi.

It is expected behavior. Because you do not yet have tasks with indixes 1 and 2.

Try this:

todo myTask1
deadline myDeadline 1 /by 10 10 2020
list

you will be able to see the task list with indices.

Then you will be able to use “add” command to add tasks with indices to the modules.

Best Regards
Bozhao

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by TomLBZ** [comment]
> <img alt="Screenshot 2020-10-30 at 4 14 18 PM" width="1440" src="https://user-images.githubusercontent.com/60168552/97678773-531e9e00-1acf-11eb-93f1-4ff576f28751.png">
> 
> Hi, I am trying to use your application, I followed how to use the add command, but I cannot use it

Should you need any further clarification please do not hesitate to keep commenting on this thread.

**Comment by TomLBZ** [comment]
> <img alt="Screenshot 2020-10-30 at 4 14 18 PM" width="1440" src="https://user-images.githubusercontent.com/60168552/97678773-531e9e00-1acf-11eb-93f1-4ff576f28751.png">
> 
> Hi, I am trying to use your application, I followed how to use the add command, but I cannot use it

In short, you need to ***create tasks before trying to add tasks to modules***. The program works as expected in showing "NOT FOUND" when no specified task can be found, and showing "index out of range" when your specified index is indeed out of range. Those are expected error handling behaviors.

**Comment by domaxi** [comment]
I think it is a little bit counter-intuitive because the user do not have any specific instruction in the UG or in the help page on how to add new tasks. Your add command makes it more confusing for the user to add the tasks.

**Comment by TomLBZ** [comment]
> I think it is a little bit counter-intuitive because the user do not have any specific instruction in the UG or in the help page on how to add new tasks. Your add command makes it more confusing for the user to add the tasks.

Thank you for your valuable feedback. Please report this unintuitive documentation on CATcher as a Documentation Bug. We will improve the UG in the future based on your advice. (this shows that we have not written the UG truly from a user prospective, and we will consider adding a short "usage example" session before the feature list in the next version of UG) Thanks!

**Comment by scjx123** [comment]
Closed with UG Diagram explanation.
