### ISSUE TITLE
Unable to add to the list 

### ISSUE THREAD

**Issue by Ang-Cheng-Jun** [AY2021S1-CS2113-T13-2/tp#220]
I used the exact same command as the example, still cannot add

**Comment by TomLBZ** [comment]
> I used the exact same command as the example, still cannot add

Hi. Would you mid providing a screenshot?

Firstly, you must indeed have tasks before you can try to add tasks to modules, otherwise of course the program need to show an error message.

Try this:

todo testTask1
todo testTask2
todo testTask3
list

Then you should be able to see that you have some tasks in the task list.
then, you can add the specified tasks to specified modules:

add -task 1 2 -mod EE2026

Should you need further clarifications, please do not hesitate to respond to this thread. Thanks!

**Comment by scjx123** [comment]
note that if you added duplicated task, it will not be added to the list.

**Comment by Ang-Cheng-Jun** [comment]
![image](https://user-images.githubusercontent.com/69335512/97690514-08edea80-1ad8-11eb-913c-00f7b79f250f.png)
Here you go, i redownloaded it

**Comment by TomLBZ** [comment]
> ![image](https://user-images.githubusercontent.com/69335512/97690514-08edea80-1ad8-11eb-913c-00f7b79f250f.png)
> Here you go, i redownloaded it

This is working perfectly fine as expected... because ***for your newly downloaded jar there is ZERO TASK created, and the index 1 and 2 are SURELY out of range.*** 

You can try reading my previous reply.

For your convenience I am going to paste it here:
````
Firstly, you must indeed have tasks before you can try to add tasks to modules, otherwise of course the program need to show an error message.

Try this:

todo testTask1
todo testTask2
todo testTask3
list

Then you should be able to see that you have some tasks in the task list.
then, you can add the specified tasks to specified modules:

add -task 1 2 -mod EE2026

Should you need further clarifications, please do not hesitate to respond to this thread. Thanks!
```

**Comment by scjx123** [comment]
1 2 is NOT referring to the task name itself. if you look at our UG, you would see that it is actually an indices. meaning, if u type list, and you see 
1. eat food 
2. deadline meeting (by: Dec 12 2020 19:40)

u can proceed to use this command to add the task 1 AND 2 into both module CS2113 and CS2113T

**Comment by TomLBZ** [comment]
> ![image](https://user-images.githubusercontent.com/69335512/97690514-08edea80-1ad8-11eb-913c-00f7b79f250f.png)
> Here you go, i redownloaded it

In other words, this is a High Severity Documentation Bug (as Prof says), because our documentation is unclear. Please report this, thanks

**Comment by scjx123** [comment]
> ![image](https://user-images.githubusercontent.com/69335512/97690514-08edea80-1ad8-11eb-913c-00f7b79f250f.png)
> Here you go, i redownloaded it

1 2 is NOT referring to the task name itself. if you look at our UG, you would see that it is actually an indices. meaning, if u type list, and you see 
1. eat food 
2. deadline meeting (by: Dec 12 2020 19:40)

u can proceed to use this command to add the task 1 AND 2 into both module CS2113 and CS2113T

**Comment by TomLBZ** [comment]
> 1 2 is NOT referring to the task name itself. if you look at our UG, you would see that it is actually an indices. meaning, if u type list, and you see
> 
> 1. eat food
> 2. deadline meeting (by: Dec 12 2020 19:40)
> 
> u can proceed to use this command to add the task 1 AND 2 into both module CS2113 and CS2113T

Yes you are right. that's why its showing "Index out of range" instaed of "[NOT FOUND]".

**Comment by Ang-Cheng-Jun** [comment]
Your UG is too hard to understand. Maybe you should make it clearly

**Comment by TomLBZ** [comment]
> Your UG is too hard to understand. Maybe you should make it clearly

Yes indeed, our UG is not clear. Please report it as a High Severity Documentation Bug.

**Comment by Ang-Cheng-Jun** [comment]
Btw, i have ask prof. He ask me to do on fallback team already. So i cant create an issue on it.

**Comment by TomLBZ** [comment]
> Btw, i have ask prof. He ask me to do on fallback team already. So i cant create an issue on it.

It is OK, we can improve the UG to make it clearer based on your valuable feedback in this issue. Thanks! Your comments really made us understand more from the user's perspective!

**Comment by scjx123** [comment]
Closed with UG Diagram explanation.
