### ISSUE TITLE
Enhance Focus command

### ISSUE THREAD

**Issue by johanesrafael** [AY2021S1-CS2113-T13-2/tp#24]
Focus command needs to be case-insensitive and more sorted

**Comment by scjx123** [comment]
Associate this issue with milestone 1
label : priority high + task
author : Rafael & Chu han
Description: recommend to split this into 2 different smaller issue as per UG. eg. 
1) Ability to focus on todo
2) Ability to focus on deadline

**Comment by johanesrafael** [comment]
Splitted into smaller issues
