### ISSUE TITLE
Todo, Done, Delete, Undone no-description message

### ISSUE THREAD

**Issue by adinata15** [AY2021S1-CS2113-T13-2/tp#258]
![image](https://user-images.githubusercontent.com/48993548/97945734-55307780-1dc3-11eb-8253-5103ebbf981a.png)
Use invalid command exception for the message instead of the IndexOutOfBound exception when no description is put in.

**Comment by TomLBZ** [comment]
![image](https://user-images.githubusercontent.com/26886705/98423188-d55b2380-20c8-11eb-91f0-3df2c647476d.png)
Fixed.
Will close this in the next PR.
