### ISSUE TITLE
Postpone no-description message

### ISSUE THREAD

**Issue by adinata15** [AY2021S1-CS2113-T13-2/tp#259]
![image](https://user-images.githubusercontent.com/48993548/97946074-439b9f80-1dc4-11eb-9447-e70ed9bb4f8d.png)

Use invalid command exception for the message instead of the IndexOutOfBound exception when no description is put in.

**Comment by TomLBZ** [comment]
![image](https://user-images.githubusercontent.com/26886705/98436277-0a8d6300-2115-11eb-8743-2e4d1c2fc9e1.png)
Fixed.
Will close in the next PR.
