### ISSUE TITLE
Include prerequisite and notes for all commands in **UserGuide and DeveloperGuide**

### ISSUE THREAD

**Issue by adinata15** [AY2021S1-CS2113-T13-2/tp#262]
Include command prerequisite and notes for all actions on **UserGuide and DeveloperGuide**. Also, handle these cases in your **code** as the user will definitely try them (i.e. print different custom message for each edge cases/exceptions).
Prerequisite: condition/command that needed to be run before carrying the specified action.
Eg: `take` some modules before running `cap`.
Notes: edge cases/things user need to take note of about the program
Eg: negative values in `goal` means the user needs to have a lower score to achieve their dream cap.
![image](https://user-images.githubusercontent.com/48993548/97947057-13093500-1dc7-11eb-98c6-00e03e7077c6.png)

**Comment by TomLBZ** [comment]
![image](https://user-images.githubusercontent.com/26886705/98404754-20b00a80-20a6-11eb-94ff-9780dd82c9cf.png)
Fixed.
Will close this in the next PR.

**Comment by TomLBZ** [comment]
Please fill up the HelpText after I merge this PR. DO NOT EDIT HELPTEXT BEFORE MERGING THIS PR.
