### ISSUE TITLE
`event` and `deadline`  no description and time response

### ISSUE THREAD

**Issue by adinata15** [AY2021S1-CS2113-T13-2/tp#263]
Error response messages for no description in `event` and `deadline` can be improved.
![image](https://user-images.githubusercontent.com/48993548/97947850-988de480-1dc9-11eb-8e31-92fd19073d50.png)

Error response messages for no time in `event` and `deadline` can be improved.
![image](https://user-images.githubusercontent.com/48993548/97947936-dc80e980-1dc9-11eb-91d2-41a0a734fda2.png)

For both cases, throwing command exception will be enough.

**Comment by TomLBZ** [comment]
![image](https://user-images.githubusercontent.com/26886705/98386203-dc634100-208a-11eb-87ad-75548684fe94.png)
fixed.
will be closed with the next pr soon.
