### ISSUE TITLE
Postpone response message can be improved and need add pre-requisite

### ISSUE THREAD

**Issue by adinata15** [AY2021S1-CS2113-T13-2/tp#264]
![image](https://user-images.githubusercontent.com/48993548/97948284-0d155300-1dcb-11eb-8c02-181ea46f87ff.png)

![image](https://user-images.githubusercontent.com/48993548/97948428-8c0a8b80-1dcb-11eb-9c19-30f80620ab3a.png)
- Add prerequisite for `postpone` action. 
- Response message can be improved so the user can know what is wrong.

**Comment by TomLBZ** [comment]
![image](https://user-images.githubusercontent.com/26886705/98436707-81782b00-2118-11eb-914a-3abe75e85208.png)
![image](https://user-images.githubusercontent.com/26886705/98436708-8a68fc80-2118-11eb-9643-9104cb98a0d8.png)
Fixed.
Will close in next PR.
