### ISSUE TITLE
Remind function unknown behaviour

### ISSUE THREAD

**Issue by adinata15** [AY2021S1-CS2113-T13-2/tp#276]
![image](https://user-images.githubusercontent.com/48993548/98446129-7348ff80-2156-11eb-9a26-22da4811effd.png)
Remind function unknown usage.

**Comment by johanesrafael** [comment]
Chuhan and I agreed to remove this function since it needs some development to finalize the expected behavior and it was not peer-reviewed last week.

**Comment by adinata15** [comment]
Ohh ok, I will remove it
