### ISSUE TITLE
Inappropriate response when no command is put in

### ISSUE THREAD

**Issue by adinata15** [AY2021S1-CS2113-T13-2/tp#279]
![image](https://user-images.githubusercontent.com/48993548/98448614-3980f480-2168-11eb-9eb7-bc7de64be736.png)
Can redirect this InvalidCommandException.

**Comment by TomLBZ** [comment]
![image](https://user-images.githubusercontent.com/26886705/98470318-ca66d700-221f-11eb-9910-b09dc92fbbf5.png)
Fixed. Closing soon.
