### ISSUE TITLE
Clear function still works when random option is put in after clear

### ISSUE THREAD

**Issue by adinata15** [AY2021S1-CS2113-T13-2/tp#280]
![image](https://user-images.githubusercontent.com/48993548/98448785-b1035380-2169-11eb-8d6a-60394ee86d14.png)
We can actually make this a feature that says it will ignore unrelated additional command unless it is fancy or we can throw invalid command.

**Comment by TomLBZ** [comment]
![image](https://user-images.githubusercontent.com/26886705/98470120-9e972180-221e-11eb-9ffc-6a65a12f1db0.png)
Fixed. Will close soon.
