### ISSUE TITLE
Complete completed task message

### ISSUE THREAD

**Issue by adinata15** [AY2021S1-CS2113-T13-2/tp#281]
![image](https://user-images.githubusercontent.com/48993548/98449033-54a13380-216b-11eb-9554-ac5e2dbccd66.png)
Although the word completed is already there, it is good to just add completed on the error message to ensure the user is really clear.

**Comment by TomLBZ** [comment]
![image](https://user-images.githubusercontent.com/26886705/98469781-a229a900-221c-11eb-99e6-904efe12be3c.png)
Fixed. Closing soon
