### ISSUE TITLE
Add completed tasks region on diagram

### ISSUE THREAD

**Issue by adinata15** [AY2021S1-CS2113-T13-2/tp#283]
![image](https://user-images.githubusercontent.com/48993548/98449410-5f10fc80-216e-11eb-9acf-9384f9f65d85.png)
NB: completed is different from taken modules

**Comment by TomLBZ** [comment]
No, this is incorrect. The program only maintains 2 data lists, list of tasks and list of ALL modules.
It also maintains a dynamic list, the "target" list (linked by reference to the 2 data lists).
"focus" on other apparent lists (selected, taken, completed, etc.) just applies filters to the 2 data lists and collect the results to the "target" list.
All operations are directly operating the "target" list, with their effects propogating back to the data lists.

**Comment by scjx123** [comment]
I have amended the UG explaining this. @adinata15 this diagram only serve as building user's intuition to use our app, it is not meant to be a ppt overview of 'dynamic' list. For that matter, the user can in fact read the `focus` section to see all the dynamic list we have, in which i have specified this in the UG.
