### ISSUE TITLE
Unknown command can be removed from userGuide

### ISSUE THREAD

**Issue by adinata15** [AY2021S1-CS2113-T13-2/tp#284]
![image](https://user-images.githubusercontent.com/48993548/98449590-b19ee880-216f-11eb-80f1-cc1363899ee8.png)

**Comment by TomLBZ** [comment]
Does it cause additional errors or confusion if we keep it there?

**Comment by adinata15** [comment]
Hmm, actually no harm keeping it there. Just that previously I thought it might be redundant.
