### ISSUE TITLE
Complete multiple "completed" command inaccurate error message

### ISSUE THREAD

**Issue by adinata15** [AY2021S1-CS2113-T13-2/tp#285]
![image](https://user-images.githubusercontent.com/48993548/98450357-20337480-2177-11eb-9d63-67f728c0caae.png)
Both modules above are already completed.

**Comment by TomLBZ** [comment]
![image](https://user-images.githubusercontent.com/26886705/98469540-3b57c000-221b-11eb-929d-e49830bdb918.png)
I cannot reproduce it. Can you provide more information?

**Comment by adinata15** [comment]
Hmm, I cannot reproduce. It works fine now. Previously, if the tasks are already completed and we complete again it comes out that error but now no more. Can just close this issue then 👍🏻
