### ISSUE TITLE
Add layout information on Fancy layout

### ISSUE THREAD

**Issue by adinata15** [AY2021S1-CS2113-T13-2/tp#287]
![image](https://user-images.githubusercontent.com/48993548/98451200-8a9be300-217e-11eb-94a4-0d7301a1f1a7.png)
It will be great to add more explanation on what each the region on the fancy UI represents int he UG!

**Comment by TomLBZ** [comment]
![image](https://user-images.githubusercontent.com/26886705/98469427-6b529380-221a-11eb-9d7b-080b199f855c.png)
Fixed. Closing soon.
