### ISSUE TITLE
Plain function return last called function

### ISSUE THREAD

**Issue by adinata15** [AY2021S1-CS2113-T13-2/tp#288]
![image](https://user-images.githubusercontent.com/48993548/98451315-83290980-217f-11eb-9735-73ad4b35bed7.png)
I am unsure but is this intended?

**Comment by TomLBZ** [comment]
![image](https://user-images.githubusercontent.com/26886705/98469325-d2bc1380-2219-11eb-81af-23bdf1d90260.png)
Fixed. Will close soon.
