### ISSUE TITLE
Prev and next unusual response on plain UI

### ISSUE THREAD

**Issue by adinata15** [AY2021S1-CS2113-T13-2/tp#289]
![image](https://user-images.githubusercontent.com/48993548/98451388-195d2f80-2180-11eb-80df-ebb1e0daaeea.png)
![image](https://user-images.githubusercontent.com/48993548/98451580-09dee600-2182-11eb-8d8e-372a710c09e3.png)

**Comment by TomLBZ** [comment]
![image](https://user-images.githubusercontent.com/26886705/98468569-07c66700-2216-11eb-8856-d72b0e6de1c8.png)
 Fixed. Will close soon.
