### ISSUE TITLE
EditAction that modifies attributes of a task or a module

### ISSUE THREAD

**Issue by scjx123** [AY2021S1-CS2113-T13-2/tp#29]
Associate this issue with milestone 1
label : priority high + task
author : bozhao

**Comment by TomLBZ** [comment]
I intend to do it like:
edit [-type] [index] [field=newvalue] ...
for example:
edit -task 1 description=blahblahblah date=blabhblh
edit -mod 5 MC=4

Pre-requisites: the target item must be selected. If it is not selected, it will be automatically selected.

Related: Need to implement "unselect" and "untake". Planning to use base actions.

**Comment by TomLBZ** [comment]
Also, the edit should be able to change tasks for a module:
edit -mod 5 updateTask
will set the task of module 5 to be tasks currently in the selected list.
If nothing is selected, this will clear the task for module 5.
