### ISSUE TITLE
delete function out of index 

### ISSUE THREAD

**Issue by chuhann** [AY2021S1-CS2113-T13-2/tp#305]
delete function out of index when deleting index more than index size
![image](https://user-images.githubusercontent.com/13757965/98521789-e1a0d580-22ae-11eb-8b9d-e6db8abc4300.png)

**Comment by TomLBZ** [comment]
This is working correctly. Where is the bug?

**Comment by chuhann** [comment]
As in the error msg to be more specific ?

**Comment by TomLBZ** [comment]
I feel that "index out of range" is exactly what the problem is...
How to make it more specific? Do you have any suggestions?

**Comment by chuhann** [comment]
I guess its okay since both delete and done has the same standardized error msg

**Comment by TomLBZ** [comment]
OK! Thanks for testing out the program!
