### ISSUE TITLE
'back' function 

### ISSUE THREAD

**Issue by scjx123** [AY2021S1-CS2113-T13-2/tp#31]
Associate this issue with milestone 1
label : priority high + task
author : bozhao 
description : Switch the content in the item list region from detail mode or edit mode to the default view (list).

**Comment by TomLBZ** [comment]
The back function should be implemented after implementing the "Edit" function, otherwise it is useless. Shall we move it to the next iteration?

**Comment by TomLBZ** [comment]
Back function is no longer needed. Just use focus. Closing this with my PR.
